# Generated by Django 5.1.6 on 2025-03-07 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trave', '0002_alter_usuario_senha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aeroporto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_aeroporto', models.CharField(max_length=10, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Voo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_voo', models.CharField(max_length=20, unique=True)),
                ('data_partida', models.DateTimeField()),
                ('data_chegada', models.DateTimeField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('assentos_disponiveis', models.IntegerField()),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voos_chegada', to='trave.aeroporto')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voos_partida', to='trave.aeroporto')),
            ],
        ),
    ]
