# Generated by Django 5.1.6 on 2025-03-09 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trave', '0003_aeroporto_voo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aeroporto',
            name='estado',
            field=models.CharField(default='Desconhecido', max_length=50),
        ),
    ]
